version: '3.7'
services:
  jenkins:
    container_name: jenkins-ansible
    image: jenkins
    build:
      context: ./
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
    networks:
      - net
  remote_host:
    container_name: remote-host
    networks: 
      - net
    image: remote-host
    build: 
      context: ssh_server
  git:
    container_name: git-server
    image: 'gitlab/gitlab-ee:latest' 
    hostname: 'gitlab.example.com'  
    ports:
        - '8090:80'      
    volumes:
        - '$GITLAB_HOME/config:/etc/gitlab'
        - '$GITLAB_HOME/logs:/var/log/gitlab'
        - '$GITLAB_HOME/data:/var/opt/gitlab'
    networks:
        net:
networks:
    net:
